from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00a5bf327eab'
down_revision: Union[str, None] = '5fd279e06f15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_logins', sa.Column('user_device_type', sa.Text(), nullable=False))
    op.create_unique_constraint(None, 'user_logins', ['id', 'user_device_type'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_logins', type_='unique')
    op.drop_column('user_logins', 'user_device_type')
    # ### end Alembic commands ###
