"""add cascade for foreign keys

Revision ID: 5fd279e06f15
Revises: c28228fd0e3f
Create Date: 2024-06-06 11:34:13.680365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5fd279e06f15'
down_revision: Union[str, None] = 'c28228fd0e3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('roles', 'name',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('user_logins', 'user_agent',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_constraint('user_logins_user_id_fkey', 'user_logins', type_='foreignkey')
    op.create_foreign_key(None, 'user_logins', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('user_role_user_id_fkey', 'user_role', type_='foreignkey')
    op.drop_constraint('user_role_role_id_fkey', 'user_role', type_='foreignkey')
    op.create_foreign_key(None, 'user_role', 'roles', ['role_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_role', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'hashed_password',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_constraint(None, 'user_role', type_='foreignkey')
    op.drop_constraint(None, 'user_role', type_='foreignkey')
    op.create_foreign_key('user_role_role_id_fkey', 'user_role', 'roles', ['role_id'], ['id'])
    op.create_foreign_key('user_role_user_id_fkey', 'user_role', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'user_logins', type_='foreignkey')
    op.create_foreign_key('user_logins_user_id_fkey', 'user_logins', 'users', ['user_id'], ['id'])
    op.alter_column('user_logins', 'user_agent',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('roles', 'name',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    # ### end Alembic commands ###
