"""make user agent optional

Revision ID: c28228fd0e3f
Revises: 75f3ca85da23
Create Date: 2024-06-01 16:53:11.827475

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c28228fd0e3f'
down_revision: Union[str, None] = '75f3ca85da23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_logins', 'user_agent',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_logins', 'user_agent',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
