version: '3'

services:
  redis:
    image: redis:7.2.4
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    expose:
      - "6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  pg:
    image: postgres:16
    volumes:
      - pg_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    expose:
      - "5432"
    env_file:
      - ../auth-service/.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app"]
      interval: 5s
      timeout: 5s
      retries: 5

  jaeger:
    image: jaegertracing/all-in-one:1.58
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"
    expose:
      - "16686"
      - "4317"
      - "4318"

volumes:
  pg_data:
  redis_data:
