version: '3'

services:
  auth_redis:
    image: redis:7.2.4
    volumes:
      - auth_redis_data:/data
    expose:
      - "6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  auth_pg:
    image: postgres:16
    volumes:
      - auth_pg_data:/var/lib/postgresql/data/
    expose:
      - "5432"
    env_file:
      - ../auth-service/.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app"]
      interval: 5s
      timeout: 5s
      retries: 5

  auth_jaeger:
    image: jaegertracing/all-in-one:1.58
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - "16686:16686"
    expose:
      - "16686"
      - "4317"
      - "4318"

  auth_service:
    build: ../auth-service
    expose:
      - "8000"
    env_file:
      - ../auth-service/.env
    depends_on:
      auth_jaeger:
        condition: service_started
      auth_pg:
        condition: service_healthy
      auth_redis:
        condition: service_healthy

  auth_nginx:
    image: nginx:1.25.3
    volumes:
      - ../nginx/nginx.conf:/etc/nginx/nginx.conf
      - ../nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    expose:
      - "80"
    depends_on:
      - auth_service

volumes:
  auth_pg_data:
  auth_redis_data:
